// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIftrjPbDCv9DYQcfbzz6sS5mjxZYtJ6I',
    appId: '1:427072760123:android:40d14b8711c967be482f1e',
    messagingSenderId: '427072760123',
    projectId: 'flutter-chat-app-72acc',
    databaseURL: 'https://flutter-chat-app-72acc-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-72acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWYi0qqCwa97bWGRWp0R5b7jHh3fuuGBQ',
    appId: '1:427072760123:ios:97f2feda0b3a493e482f1e',
    messagingSenderId: '427072760123',
    projectId: 'flutter-chat-app-72acc',
    databaseURL: 'https://flutter-chat-app-72acc-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-72acc.appspot.com',
    iosClientId: '427072760123-8dueiu2uj84mvrgm7t10459f76a5sm47.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
